### ISSUE TITLE
Error:(75, 0) Could not get unknown property 'GROUP' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.

### ISSUE THREAD

**Issue by MantraUser** [nisrulz/easydeviceinfo#21]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Error:(75, 0) Could not get unknown property 'GROUP' for object of type org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.
<a href="openFile:D:\Nilesh\Utility workspace\easydeviceinfo-2.4.0\easydeviceinfo\build.gradle">Open File</a>
**If the current behavior is a bug, please provide the steps to reproduce.**

**Any logs, error output, bugreport etc?**

**What is the expected behavior?**

**Any other comments?**

ALSO POM VALUES ARE MISSING
<--
 developerId = POM_DEVELOPER_ID
  developerName = POM_DEVELOPER_NAME
  developerEmail = POM_DEVELOPER_EMAILID

  licenseName = POM_LICENCE_NAME
  licenseUrl = POM_LICENCE_URL
  allLicenses = [POM_ALL_LICENCES]
-->
sims like maven dependency missing
how to resolve
**What versions of software are you using?**
+ **Device Information:** 

+ **Android Version:** 

+ **Configuration Information:** 

+ **Misc:**

**Comment by nisrulz** [comment]
@MantraUser Could you explain to me what are you trying to do, when you get this error. The reason those values are not checked in is because they are used to publish the library to JCenter. If you compile the app and library should work without any issue. The values cannot be shared because they define the ownership of the library to me in JCenter, otherwise anyone would be able to publish it to the namespace and break the build for everyone.

**Comment by MantraUser** [comment]
i was trying to build cloned project i want to use it as seperate module but now i know that i can improt only library module, Thanks

**Comment by nisrulz** [comment]
Ok. I guess that solves your issue. Closing this issue for now.

**Comment by maheshwariaanchal** [comment]
Cannot we clone this project from GitHub? Because when I am cloning the project I am unable to build it and see the output.
